"""c:/PROJECTS/PYTHON/FLASK/REPORT_IT/env/Scripts/python.exe c:/PROJECTS/PYTHON/FLASK/REPORT_IT/db_migration.py

Revision ID: 2bc767b75629
Revises: d782268c84f4
Create Date: 2025-11-17 16:29:16.987642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc767b75629'
down_revision = 'd782268c84f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_type_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('report_file', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_reports_report_file', ['report_file'])
        batch_op.create_foreign_key('fk_reports_report_type_id', 'reporttype', ['report_type_id'], ['id'])
        batch_op.drop_column('report_content')
        batch_op.drop_column('report_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_type', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('report_content', sa.TEXT(), nullable=True))
        batch_op.drop_constraint('fk_reports_report_type_id', type_='foreignkey')
        batch_op.drop_constraint('uq_reports_report_file', type_='unique')
        batch_op.drop_column('report_file')
        batch_op.drop_column('report_type_id')

    # ### end Alembic commands ###
